<template>
  <div class="space-y-6">
    <div class="flex flex-wrap items-end justify-between gap-4"><div><p class="text-xs font-semibold uppercase tracking-[0.16em] text-amber-700">Public giving</p><h1 class="mt-1 text-2xl font-semibold">Fundraising campaigns</h1><p class="mt-1 text-sm text-slate-500">Create the public donation posts that organisations can share.</p></div><button @click="showForm = true" class="rounded-lg bg-[#0d1d2d] px-4 py-2.5 text-sm font-semibold text-white">+ New fundraiser</button></div>
    <section class="rounded-xl border bg-white shadow-sm"><div class="border-b p-5"><h2 class="font-semibold">Pending donation references</h2><p class="mt-1 text-sm text-slate-500">Verify mobile money references before they appear in finance totals.</p></div><div v-for="donation in donations" :key="donation.id" class="flex flex-wrap items-center justify-between gap-4 border-b p-5 last:border-0"><div><div class="font-semibold">{{ donation.campaign?.title }}</div><div class="text-sm text-slate-500">{{ donation.donor_name || 'Anonymous donor' }} · {{ donation.donor_phone || 'No phone' }} · Ref {{ donation.last5_reference || 'missing' }}</div></div><div class="flex items-center gap-3"><strong>UGX {{ Number(donation.amount_ugx).toLocaleString() }}</strong><button @click="verify(donation, 'paid')" class="rounded-lg bg-emerald-700 px-3 py-2 text-xs font-semibold text-white">Approve</button><button @click="verify(donation, 'rejected')" class="rounded-lg border border-red-200 px-3 py-2 text-xs text-red-700">Reject</button></div></div><div v-if="!donations.length" class="p-6 text-sm text-slate-500">No pending donation references.</div></section>
    <div class="grid gap-4 md:grid-cols-2"><article v-for="campaign in campaigns" :key="campaign.id" class="overflow-hidden rounded-xl border bg-white shadow-sm"><img v-if="campaign.photo_url" :src="campaign.photo_url" :alt="campaign.title" class="h-40 w-full object-cover" /><div class="p-5"><div class="flex justify-between gap-3"><span class="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold uppercase text-slate-600">{{ campaign.status }}</span><span class="text-xs text-slate-500">{{ campaign.organization?.name }}</span></div><h2 class="mt-3 text-lg font-semibold">{{ campaign.title }}</h2><p class="mt-2 line-clamp-3 text-sm text-slate-600">{{ campaign.summary }}</p><div class="mt-4 flex flex-wrap gap-2"><RouterLink v-if="campaign.status === 'published'" :to="`/donate/${campaign.slug}`" target="_blank" class="rounded-lg bg-emerald-700 px-3 py-2 text-xs font-semibold text-white">Open public post</RouterLink><button v-if="campaign.status !== 'published'" @click="publish(campaign)" class="rounded-lg border border-emerald-200 px-3 py-2 text-xs font-semibold text-emerald-700">Publish</button></div></div></article></div>
    <div v-if="!campaigns.length" class="rounded-xl border border-dashed bg-white p-10 text-center text-sm text-slate-500">No fundraising campaigns yet.</div>
    <div v-if="showForm" class="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4" @click.self="showForm = false"><form @submit.prevent="save" class="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-6"><div class="flex justify-between"><div><h2 class="text-xl font-semibold">New fundraiser</h2><p class="mt-1 text-sm text-slate-500">A photo and message make the shared donation link clear.</p></div><button type="button" @click="showForm = false" class="text-2xl text-slate-400">×</button></div><div class="mt-5 grid gap-4"><input v-model="form.title" required placeholder="Campaign title" class="rounded-lg border p-3" /><textarea v-model="form.summary" required rows="2" placeholder="Short summary" class="rounded-lg border p-3"></textarea><textarea v-model="form.message" required rows="8" placeholder="Full message to supporters" class="rounded-lg border p-3"></textarea><input v-model.number="form.target_amount_ugx" type="number" min="100" placeholder="Target amount in UGX (optional)" class="rounded-lg border p-3" /><label class="flex items-center gap-2 text-sm"><input v-model="form.show_progress" type="checkbox" /> Show “Raised so far” on the public post</label><input required type="file" accept="image/*" @change="selectPhoto" class="rounded-lg border p-2 text-sm" /><img v-if="preview" :src="preview" alt="Fundraiser photo preview" class="h-40 w-full rounded-lg object-cover" /><label class="flex items-center gap-2 text-sm"><input v-model="form.status" type="checkbox" true-value="published" false-value="draft" /> Publish immediately</label></div><p v-if="error" class="mt-4 text-sm text-red-700">{{ error }}</p><div class="mt-6 flex justify-end gap-2"><button type="button" @click="showForm = false" class="rounded-lg border px-4 py-2">Cancel</button><button :disabled="saving" class="rounded-lg bg-[#0d1d2d] px-4 py-2 font-semibold text-white">{{ saving ? 'Saving...' : 'Save fundraiser' }}</button></div></form></div>
  </div>
</template>
<script setup>
import { onMounted, ref } from 'vue'
import api from '../api/client'
const campaigns = ref([]), donations = ref([]), showForm = ref(false), saving = ref(false), error = ref(''), photo = ref(null), preview = ref('')
const emptyForm = () => ({ title: '', summary: '', message: '', target_amount_ugx: null, show_progress: true, status: 'draft' })
const form = ref(emptyForm())
async function load() { const [{ data: campaignData }, { data: donationData }] = await Promise.all([api.get('/admin/fundraisers'), api.get('/admin/fundraising-donations/pending')]); campaigns.value = campaignData.data || campaignData; donations.value = donationData.data || donationData }
function selectPhoto(event) { photo.value = event.target.files[0] || null; preview.value = photo.value ? URL.createObjectURL(photo.value) : '' }
async function save() { saving.value = true; error.value = ''; try { const upload = new FormData(); upload.append('photo', photo.value); const photoResponse = await api.post('/admin/fundraisers/photo', upload, { headers: { 'Content-Type': 'multipart/form-data' } }); await api.post('/admin/fundraisers', { ...form.value, photo_url: photoResponse.data.url }); showForm.value = false; form.value = emptyForm(); await load() } catch (e) { error.value = e.response?.data?.message || 'Could not save fundraiser.' } finally { saving.value = false } }
async function publish(campaign) { await api.post(`/admin/fundraisers/${campaign.id}/publish`); await load() }
async function verify(donation, status) { await api.post(`/admin/fundraising-donations/${donation.id}/verify`, { status, provider_reference: donation.last5_reference }); await load() }
onMounted(load)
</script>
