<template>
  <section>
    <div class="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p class="text-xs font-semibold uppercase tracking-[0.18em] text-emerald-700">Reporting toolkit</p><h1 class="mt-1 text-3xl font-bold text-slate-900">Presentations</h1><p class="mt-2 text-slate-600">Create and manage presentation decks for partners and funders.</p></div><button @click="showCreate = true" class="rounded-xl bg-emerald-700 px-4 py-3 text-sm font-semibold text-white">New presentation</button></div>
    <div class="grid gap-4 md:grid-cols-2"><article v-for="deck in decks" :key="deck.id" class="rounded-2xl border border-emerald-100 bg-[#f9fcfa] p-5 shadow-sm"><div class="flex items-start justify-between gap-3"><div><span class="rounded-full bg-emerald-100 px-2 py-1 text-xs font-semibold capitalize text-emerald-800">{{ deck.status }}</span><h2 class="mt-3 text-lg font-semibold text-slate-900">{{ deck.title }}</h2></div><span class="text-sm text-slate-500">{{ deck.slides?.length || 0 }} slides</span></div><button @click="edit(deck)" class="mt-5 rounded-lg border border-emerald-200 px-3 py-2 text-sm font-semibold text-emerald-800">Edit deck</button></article></div><p v-if="!decks.length" class="rounded-2xl border bg-white p-8 text-center text-slate-500">No presentation decks yet.</p>
    <div v-if="showCreate" class="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4"><form @submit.prevent="save" class="w-full max-w-lg rounded-3xl bg-[#f9fcfa] p-6 shadow-2xl"><div class="flex items-center justify-between"><h2 class="text-xl font-semibold">{{ editing ? 'Edit presentation' : 'New presentation' }}</h2><button type="button" @click="close">Close</button></div><input v-model="form.title" required placeholder="Presentation title" class="mt-5 w-full"/><select v-model="form.status" class="mt-3 w-full"><option value="draft">Draft</option><option value="published">Published</option></select><textarea v-model="slidesText" required rows="8" placeholder="One slide title or note per line" class="mt-3 w-full"></textarea><p class="mt-1 text-xs text-slate-500">Each line becomes one slide note.</p><div class="mt-5 flex justify-end gap-2"><button type="button" @click="close" class="rounded-lg border px-4 py-2">Cancel</button><button class="rounded-lg bg-emerald-700 px-4 py-2 font-semibold text-white">Save presentation</button></div></form></div>
  </section>
</template>
<script setup>
import { onMounted, ref } from 'vue'
import api from '../api/client'
const decks = ref([]); const showCreate = ref(false); const editing = ref(null); const slidesText = ref(''); const form = ref({ title: '', status: 'draft', slides: [] })
async function load () { const { data } = await api.get('/presentations'); decks.value = data.data || data }
function edit (deck) { editing.value = deck; form.value = { title: deck.title, status: deck.status, slides: deck.slides || [] }; slidesText.value = (deck.slides || []).map((slide) => typeof slide === 'string' ? slide : slide.title || slide.note || '').join('\n'); showCreate.value = true }
function close () { showCreate.value = false; editing.value = null; slidesText.value = ''; form.value = { title: '', status: 'draft', slides: [] } }
async function save () { const payload = { title: form.value.title, status: form.value.status, slides: slidesText.value.split('\n').map((note) => ({ title: note.trim() })).filter((slide) => slide.title) }; if (editing.value) await api.put(`/presentations/${editing.value.id}`, payload); else await api.post('/presentations', payload); close(); await load() }
onMounted(load)
</script>
