<template><div><div class="flex items-center justify-between mb-6"><div><h1 class="text-2xl font-semibold">Knowledge Bank & Publications</h1><p class="text-sm text-slate-500">Draft, price, review and publish research. Only Super Admin can publish.</p></div><button @click="createPublication" class="rounded-lg bg-[#0d1d2d] px-4 py-2 text-white">New publication</button></div><div class="grid gap-4"><div v-for="p in items" :key="p.id" class="rounded-xl border bg-white p-5 shadow-sm"><div class="flex items-start justify-between gap-4"><div><div class="text-xs uppercase text-slate-500">{{p.status}}</div><h2 class="font-semibold">{{p.title}}</h2><p class="mt-1 text-sm text-slate-600">{{p.summary}}</p></div><button v-if="auth.isSuperAdmin && p.status!=='published'" @click="publish(p)" class="rounded-lg bg-emerald-700 px-3 py-2 text-sm text-white">Publish</button></div><div class="mt-4 flex flex-wrap gap-2"><span v-for="pkg in p.packages" :key="pkg.id" class="rounded-full bg-slate-100 px-3 py-1 text-xs">{{pkg.name}} · UGX {{Number(pkg.amount_ugx).toLocaleString()}}</span><button @click="addPackage(p)" class="rounded-full border px-3 py-1 text-xs">+ Price package</button></div></div></div></div></template>
<script setup>
import {onMounted,ref} from 'vue';import api from '../api/client';import {useAuthStore} from '../store/auth'
const auth=useAuthStore(),items=ref([])
async function load(){const {data}=await api.get('/admin/publications');items.value=data.data||data}
async function createPublication(){const title=prompt('Publication title');if(!title)return;const summary=prompt('Public summary');if(!summary)return;await api.post('/admin/publications',{title,summary,content:'',status:'draft'});load()}
async function addPackage(p){const name=prompt('Package name (e.g. Read for 2 hours)');if(!name)return;const amount=Number(prompt('Amount in UGX'));if(!amount)return;const mins=Number(prompt('Reading duration in minutes (0 for download)')||0);await api.post('/admin/publications/'+p.id+'/packages',{name,type:mins?'reading':'download',duration_minutes:mins||null,amount_ugx:amount,momo_amount_ugx:amount,allows_download:!mins,is_active:true});load()}
async function publish(p){if(confirm('Publish this report? Only Super Admin can do this.')){await api.post('/admin/publications/'+p.id+'/publish');load()}}
onMounted(load)
</script>