<template>
  <div class="min-h-screen bg-[#eef5f1]">
    <header class="bg-[#123f31] text-white shadow-lg shadow-emerald-950/10">
      <div class="mx-auto flex max-w-7xl flex-col gap-4 px-4 py-5 sm:flex-row sm:items-center sm:justify-between sm:px-5 sm:py-6">
        <div><div class="text-xl font-bold">ImpacTrace Knowledge Hub</div><div class="text-xs text-slate-300">Research · Evidence · Participation · Advocacy</div></div>
        <nav class="flex w-full flex-wrap items-center justify-start gap-2 sm:w-auto sm:justify-end">
          <RouterLink to="/donate" class="rounded-xl bg-[#e5c56b] px-5 py-3 text-sm font-bold text-[#123f31] shadow-sm transition hover:bg-[#f1d987]">Donate</RouterLink><a href="#plans" class="hidden text-sm text-slate-300 sm:inline">Plans</a>
          <a href="#issues" class="hidden text-sm text-slate-300 sm:inline">Issues</a>
          <a href="https://www.youtube.com/results?search_query=CodeToInnovate+Africa" target="_blank" rel="noopener noreferrer" class="rounded-lg border border-red-300/40 px-4 py-2 text-sm text-red-100">Watch YouTube</a>
          <RouterLink to="/login" class="rounded-lg border border-white/20 px-4 py-2 text-sm">Organisation Login</RouterLink>
          <button @click="openAuth('login')" class="rounded-lg bg-[#e5c56b] px-4 py-2 text-sm font-semibold text-[#123f31] shadow-sm">Sign in / Register</button>
        </nav>
      </div>
    </header>
    <main class="mx-auto max-w-7xl px-5 py-8">
      <div class="mb-8 rounded-2xl border border-emerald-100 bg-[#f9fcfa] p-6 shadow-sm sm:p-8">
        <p class="text-xs font-semibold uppercase tracking-[0.18em] text-emerald-700">ImpacTrace Knowledge Hub</p><h1 class="mt-2 text-3xl font-bold text-slate-900">Research and evidence you can use</h1>
        <p class="mt-2 max-w-3xl text-slate-600">Explore published research, surveys, district development plans, community evidence and advocacy issues. Read the public summary, then unlock the full report when needed.</p>
        <div class="mt-5 flex flex-col gap-2 sm:flex-row"><input v-model="q" @keyup.enter="load" placeholder="Search reports, issues, districts..." class="min-w-0 flex-1 rounded-xl border px-4 py-3"/><button @click="load" class="rounded-xl bg-[#0d1d2d] px-5 py-3 text-white">Search</button></div>
      </div>
      <div v-if="loading" class="text-slate-500">Loading publications…</div>
      <div class="grid gap-5 md:grid-cols-2 lg:grid-cols-3">
        <article v-for="p in items" :key="p.id" class="overflow-hidden rounded-2xl border border-emerald-100 bg-[#f9fcfa] shadow-sm">
          <div class="h-32 bg-slate-200" :style="p.cover_image ? {backgroundImage:`url(${p.cover_image})`,backgroundSize:'cover',backgroundPosition:'center'} : {}"></div>
          <div class="p-5"><div class="text-xs uppercase tracking-wider text-slate-500">{{ p.category || 'Research' }}</div><h2 class="mt-1 text-lg font-semibold">{{ p.title }}</h2><p class="mt-2 text-sm text-slate-600 line-clamp-3">{{ p.summary }}</p><RouterLink :to="`/publications/${p.slug}`" class="mt-4 inline-block font-semibold text-[#0d1d2d]">Read more →</RouterLink></div>
        </article>
      </div>
      <div v-if="!loading && !items.length" class="rounded-xl border bg-white p-8 text-center text-slate-500">No published reports matched your search.</div>
      <section v-if="fundraisers.length" id="fundraisers" class="mt-10 rounded-2xl border border-amber-100 bg-[#fffdf6] p-5 sm:p-7"><div class="flex items-end justify-between gap-4"><div><div class="text-xs font-semibold uppercase tracking-widest text-amber-700">Support local action</div><h2 class="mt-1 text-2xl font-bold text-slate-900">Donate to a cause</h2></div><span class="text-sm text-slate-500">Every contribution counts</span></div><div class="mt-5 grid gap-4 md:grid-cols-3"><article v-for="campaign in fundraisers" :key="campaign.id" class="overflow-hidden rounded-xl border border-amber-100 bg-white"><img v-if="campaign.photo_url" :src="campaign.photo_url" :alt="campaign.title" class="h-36 w-full object-cover" /><div class="p-4"><div class="text-xs text-emerald-700">{{ campaign.organization?.name }}</div><h3 class="mt-1 font-semibold">{{ campaign.title }}</h3><p class="mt-2 line-clamp-3 text-sm text-slate-600">{{ campaign.summary }}</p><RouterLink :to="`/donate/${campaign.slug}`" class="mt-4 inline-block rounded-lg bg-[#176b4d] px-3 py-2 text-sm font-semibold text-white">Donate</RouterLink></div></article></div></section>
      <section v-if="items.some((item) => item.youtube_url)" class="mt-10 rounded-2xl bg-[#0d1d2d] p-6 text-white shadow-sm"><div class="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><div class="text-xs font-semibold uppercase tracking-widest text-red-200">Free viewing</div><h2 class="mt-1 text-2xl font-bold">Watch our work on YouTube</h2><p class="mt-2 text-sm text-slate-300">Research stories and community voices are free to watch. Every view helps the work reach further.</p></div><a href="https://www.youtube.com/results?search_query=CodeToInnovate+Africa" target="_blank" rel="noopener noreferrer" class="font-semibold text-red-200">Open channel ↗</a></div><div class="mt-5 grid gap-3 sm:grid-cols-2"><a v-for="item in items.filter((publication) => publication.youtube_url)" :key="item.id" :href="item.youtube_url" target="_blank" rel="noopener noreferrer" class="rounded-xl border border-white/10 bg-white/5 p-4 hover:bg-white/10"><div class="text-sm font-semibold">{{ item.title }}</div><div class="mt-2 text-xs text-red-200">Watch free on YouTube ↗</div></a></div></section>
      <section id="plans" class="mt-12 rounded-2xl border border-emerald-100 bg-[#e3f1e9] p-5 sm:p-7">
        <div class="flex items-end justify-between"><div><div class="text-xs font-semibold uppercase tracking-widest text-amber-700">Local planning</div><h2 class="mt-1 text-2xl font-bold text-slate-900">Development plans</h2></div><span class="text-sm text-slate-500">Public records</span></div>
        <div class="mt-4 grid gap-4 md:grid-cols-3"><article v-for="plan in plans" :key="plan.id" class="rounded-xl border border-emerald-100 bg-[#f9fcfa] p-5"><div class="text-xs text-emerald-700">{{ plan.geography?.name || 'Community plan' }}</div><h3 class="mt-1 font-semibold">{{ plan.title }}</h3><p class="mt-2 line-clamp-3 text-sm text-slate-600">{{ plan.content || 'Published local development plan.' }}</p></article></div>
        <div v-if="!plans.length" class="mt-4 rounded-xl border bg-white p-5 text-sm text-slate-500">Published development plans will appear here.</div>
      </section>
      <section id="issues" class="mt-12 rounded-2xl border border-emerald-100 bg-[#f7fbf8] p-5 sm:p-7">
        <div class="flex items-end justify-between"><div><div class="text-xs font-semibold uppercase tracking-widest text-amber-700">Community voice</div><h2 class="mt-1 text-2xl font-bold text-slate-900">Issues in action</h2></div><span class="text-sm text-slate-500">Evidence for change</span></div>
        <div class="mt-4 grid gap-4 md:grid-cols-3"><article v-for="issue in issues" :key="issue.id" class="rounded-xl border bg-white p-5"><div class="text-xs uppercase text-emerald-700">{{ issue.status.replace('_', ' ') }}</div><h3 class="mt-1 font-semibold">{{ issue.title }}</h3><p class="mt-2 line-clamp-3 text-sm text-slate-600">{{ issue.problem || issue.evidence || 'Community advocacy issue.' }}</p></article></div>
        <div v-if="!issues.length" class="mt-4 rounded-xl border bg-white p-5 text-sm text-slate-500">Published advocacy issues will appear here.</div>
      </section>
      <section id="help" class="mt-12 rounded-2xl border border-emerald-100 bg-[#e3f1e9] p-5 sm:p-7"><div class="max-w-2xl"><div class="text-xs font-semibold uppercase tracking-widest text-emerald-700">Need help?</div><h2 class="mt-1 text-2xl font-bold text-slate-900">Talk to our support team</h2><p class="mt-2 text-sm text-slate-600">Send a question about registration, access, or payments and our team will respond.</p><form class="mt-5 grid gap-3 sm:grid-cols-2" @submit.prevent="sendSupport"><input v-model="support.name" required placeholder="Your name"/><input v-model="support.email" required type="email" placeholder="Email address"/><input v-model="support.subject" placeholder="Subject" class="sm:col-span-2"/><textarea v-model="support.message" required rows="3" placeholder="How can we help?" class="sm:col-span-2"></textarea><button class="rounded-xl bg-[#176b4d] px-4 py-3 font-semibold text-white sm:col-span-2">Send message</button></form><p v-if="supportMessage" class="mt-3 text-sm font-medium text-emerald-800">{{ supportMessage }}</p></div></section>
    </main>
    <div v-if="showRegister" class="fixed inset-0 bg-black/50 grid place-items-center p-5">
      <form @submit.prevent="register" class="w-full max-w-md rounded-2xl bg-white p-6">
        <h2 class="text-xl font-semibold">{{ authMode === 'login' ? 'Sign in to Knowledge Hub' : 'Create reader account' }}</h2><input v-if="authMode === 'register'" v-model="form.name" required placeholder="Name" class="mt-4 w-full rounded-lg border p-3"/>
        <input v-model="form.email" type="email" required placeholder="Email" class="mt-3 w-full rounded-lg border p-3"/>
        <input v-model="form.phone" placeholder="Phone" class="mt-3 w-full rounded-lg border p-3"/>
        <input v-model="form.password" type="password" required minlength="8" placeholder="Password" class="mt-3 w-full rounded-lg border p-3"/>
        <input v-if="authMode === 'register'" v-model="form.password_confirmation" type="password" required placeholder="Confirm password" class="mt-3 w-full rounded-lg border p-3"/>
        <div class="mt-4 flex gap-2"><button class="flex-1 rounded-lg bg-[#0d1d2d] p-3 text-white">{{ authMode === 'login' ? 'Sign in' : 'Register' }}</button><button type="button" @click="showRegister=false" class="rounded-lg border px-4">Cancel</button></div>
        <button type="button" @click="authMode=authMode === 'login' ? 'register' : 'login'" class="mt-3 text-sm text-[#0d1d2d] underline">{{ authMode === 'login' ? 'Create a reader account' : 'I already have an account' }}</button>
      </form>
    </div>
    <div class="fixed bottom-4 right-4 z-30 flex flex-col gap-3 sm:bottom-5 sm:right-5" aria-label="Social contacts">
      <a href="https://wa.me/256774443132" target="_blank" rel="noopener noreferrer" aria-label="Chat with COTIA on WhatsApp" title="Chat on WhatsApp" class="grid h-12 w-12 place-items-center rounded-full bg-[#25D366] text-white shadow-lg shadow-emerald-950/20 ring-4 ring-white/80 transition hover:scale-105 sm:h-14 sm:w-14"><svg viewBox="0 0 24 24" class="h-7 w-7 fill-current sm:h-8 sm:w-8" aria-hidden="true"><path d="M20.52 3.48A11.82 11.82 0 0 0 12.06 0C5.52 0 .2 5.32.2 11.86c0 2.09.55 4.13 1.59 5.93L.1 24l6.35-1.66a11.84 11.84 0 0 0 5.61 1.43h.01c6.54 0 11.86-5.32 11.86-11.86 0-3.17-1.24-6.15-3.41-8.43Zm-8.46 18.26h-.01a9.85 9.85 0 0 1-5.03-1.38l-.36-.21-3.77.99 1.01-3.67-.23-.38a9.84 9.84 0 0 1-1.51-5.23C2.16 6.43 6.59 2 12.06 2c2.65 0 5.14 1.03 7.01 2.91a9.84 9.84 0 0 1 2.9 7.01c0 5.47-4.43 9.82-9.91 9.82Zm5.41-7.37c-.3-.15-1.77-.87-2.04-.97-.27-.1-.47-.15-.67.15-.2.3-.77.97-.94 1.17-.17.2-.35.22-.65.07-.3-.15-1.26-.46-2.4-1.47-.89-.79-1.49-1.76-1.66-2.06-.17-.3-.02-.46.13-.61.14-.14.3-.35.45-.52.15-.17.2-.3.3-.5.1-.2.05-.37-.02-.52-.07-.15-.67-1.62-.92-2.22-.24-.58-.49-.5-.67-.51h-.57c-.2 0-.52.07-.79.37-.27.3-1.04 1.02-1.04 2.49s1.07 2.89 1.22 3.09c.15.2 2.1 3.21 5.09 4.5.71.31 1.26.5 1.69.64.71.23 1.36.2 1.87.12.57-.08 1.77-.72 2.02-1.42.25-.7.25-1.3.17-1.42-.07-.12-.27-.2-.57-.35Z"/></svg></a>
      <a href="https://x.com/CodetoinnovateA" target="_blank" rel="noopener noreferrer" aria-label="Follow CodeToInnovate Africa on X" title="Follow us on X" class="grid h-12 w-12 place-items-center rounded-full bg-black text-xl font-bold text-white shadow-lg shadow-slate-900/20 ring-4 ring-white/80 transition hover:scale-105 sm:h-14 sm:w-14">X</a>
    </div>
  </div>
</template>
<script setup>
import {onMounted,ref} from 'vue'; import publicApi from '../api/publicClient'
const items=ref([]),plans=ref([]),issues=ref([]),fundraisers=ref([]),q=ref(''),loading=ref(false),showRegister=ref(false),authMode=ref('login')
const form=ref({name:'',email:'',phone:'',password:'',password_confirmation:''}),support=ref({name:'',email:'',subject:'',message:''}),supportMessage=ref('')
function openAuth(mode){authMode.value=mode;showRegister.value=true}
async function load(){loading.value=true;try{const {data}=await publicApi.get('/public/publications',{params:{q:q.value}});items.value=data.data||data}catch(e){items.value=[]}finally{loading.value=false}}
async function loadPublicRecords(){const [plansResponse,issuesResponse]=await Promise.all([publicApi.get('/public/plans'),publicApi.get('/public/issues')]);plans.value=plansResponse.data.data||plansResponse.data;issues.value=issuesResponse.data.data||issuesResponse.data}
async function loadFundraisers(){try{const {data}=await publicApi.get('/public/fundraisers');fundraisers.value=data.data||data}catch(e){fundraisers.value=[]}}
async function register(){try{const endpoint=authMode.value === 'login' ? '/public/auth/login' : '/public/auth/register';const payload=authMode.value === 'login' ? {email:form.value.email,password:form.value.password}:form.value;const {data}=await publicApi.post(endpoint,payload);localStorage.setItem('public_token',data.token);showRegister.value=false;alert(authMode.value === 'login' ? 'Signed in.' : 'Account created. You can now purchase reading access.')}catch(e){const errors=e.response?.data?.errors;const detail=errors ? Object.values(errors).flat().join(' ') : e.response?.data?.message;alert(detail||'Authentication failed. Check your email and password, or create a reader account.')}}
async function sendSupport(){try{await publicApi.post('/public/support',support.value);supportMessage.value='Message sent. Our support team will respond shortly.';support.value={name:'',email:'',subject:'',message:''}}catch(e){supportMessage.value=e.response?.data?.message||'We could not send your message.'}}
onMounted(()=>{load();loadPublicRecords();loadFundraisers()})
</script>