<template>
  <div class="min-h-screen bg-[#eef5f1]">
    <header class="bg-[#123f31] p-5 text-white shadow-lg"><div class="mx-auto max-w-4xl"><RouterLink to="/" class="font-semibold">← Knowledge Hub</RouterLink></div></header>
    <main class="mx-auto max-w-4xl px-4 py-8 sm:px-5">
      <div v-if="pub">
        <div class="text-xs font-semibold uppercase tracking-[0.16em] text-teal-700">{{ pub.category || 'Research' }}</div>
        <h1 class="mt-2 text-3xl font-bold tracking-tight text-slate-900 sm:text-4xl">{{ pub.title }}</h1>
        <p class="mt-4 text-lg leading-8 text-slate-600">{{ pub.summary }}</p>
        <a v-if="pub.youtube_url" :href="pub.youtube_url" target="_blank" rel="noopener noreferrer" class="mt-5 inline-flex items-center gap-2 rounded-xl bg-red-600 px-4 py-3 text-sm font-semibold text-white shadow-sm hover:bg-red-700">Watch related video on YouTube ↗</a>
        <div class="mt-8 rounded-2xl border border-emerald-100 bg-[#f9fcfa] p-5 shadow-sm sm:p-7">
          <div v-if="hasAccess"><div class="mb-4 flex flex-wrap items-center justify-between gap-3 text-xs font-semibold text-emerald-700"><span>ACCESS ACTIVE · EXPIRES {{ access.expires_at ? new Date(access.expires_at).toLocaleString() : 'NEVER' }}</span><button v-if="access.can_download" @click="download" class="rounded-lg bg-[#0d1d2d] px-3 py-2 text-white">Download report</button></div><div class="prose max-w-none whitespace-pre-wrap">{{ pub.content }}</div></div>
          <div v-else><h2 class="text-xl font-semibold text-slate-900">Unlock the full report</h2><p class="mt-2 text-slate-600">Choose a package and payment method. Public summaries and YouTube videos remain free.</p><div class="mt-5 grid gap-3 md:grid-cols-2"><div v-for="pkg in pub.packages" :key="pkg.id" class="rounded-xl border border-slate-200 p-4"><div class="font-semibold">{{ pkg.name }}</div><div class="mt-1 text-lg">UGX {{ Number(pkg.amount_ugx).toLocaleString() }}</div><div class="text-xs text-slate-500">{{ pkg.type === 'reading' ? `${pkg.duration_minutes} minutes` : 'Download licence' }}</div><button @click="openPayment(pkg)" class="mt-3 w-full rounded-lg bg-[#0d1d2d] p-3 font-semibold text-white">Continue reading</button></div></div></div>
        </div>
      </div>
    </main>
    <div v-if="paymentOpen" class="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-3 sm:p-4" @click.self="paymentOpen = false">
      <section class="max-h-[calc(100dvh-1.5rem)] w-full max-w-md overflow-y-auto overscroll-contain rounded-3xl bg-white p-6 shadow-2xl sm:max-h-[calc(100dvh-2rem)] sm:p-8"><div class="flex items-start justify-between gap-4"><div><p class="text-xs font-semibold uppercase tracking-[0.16em] text-teal-700">Secure checkout</p><h2 class="mt-1 text-2xl font-semibold text-slate-900">Pay for access</h2></div><button @click="paymentOpen = false" class="rounded-lg border px-3 py-1 text-sm">Close</button></div><div class="mt-5 rounded-2xl bg-slate-50 p-4"><div class="text-sm text-slate-500">{{ selectedPackage?.name }}</div><div class="mt-1 text-2xl font-bold text-slate-900">UGX {{ Number(selectedPackage?.amount_ugx || 0).toLocaleString() }}</div></div><div v-if="!isReaderSignedIn" class="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">To track your reading time and restore access when you return, <button type="button" @click="goToReaderAuth" class="font-semibold underline">sign in or create a reader account</button>. Your account is only used for access and payment records.</div><label class="mt-5 block text-sm font-semibold text-slate-700">Payment method<select v-model="payment.method" class="mt-2 w-full"><option value="momo_manual">Mobile Money · merchant code</option><option value="pesapal">PesaPal · Visa or Mobile Money</option></select></label><p class="mt-2 text-xs leading-5 text-slate-500">{{ payment.method === 'momo_manual' ? 'Use the merchant code below, then enter only the last five characters of the transaction reference.' : 'PesaPal opens the secure payment gate for Visa cards and mobile money. Your card or mobile-money details are entered on PesaPal.' }}</p><div v-if="payment.method === 'momo_manual'" class="mt-4 rounded-xl border border-emerald-200 bg-emerald-50 p-4"><div class="text-xs font-semibold uppercase tracking-wide text-emerald-800">Merchant code</div><div class="mt-1 text-2xl font-bold tracking-widest text-emerald-950">{{ merchantCode || 'Loading...' }}</div><div class="mt-3 text-xs text-emerald-900">After payment, enter the last five characters of your transaction reference below.</div><input v-model="payment.last5_reference" required maxlength="5" minlength="5" placeholder="Last 5 transaction digits" class="mt-2 w-full uppercase" /></div><p v-if="paymentError" class="mt-4 rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{{ paymentError }}</p><button @click="submitPayment" :disabled="paymentLoading || (payment.method === 'momo_manual' && payment.last5_reference.length !== 5)" class="mt-5 w-full rounded-xl bg-teal-700 px-4 py-3.5 font-semibold text-white disabled:opacity-50">{{ paymentLoading ? 'Starting payment...' : payment.method === 'momo_manual' ? 'Submit mobile-money payment' : 'Open PesaPal payment gate' }}</button></section>
    </div>
  </div>
</template>
<script setup>
import { onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import publicApi from '../api/publicClient'
const route = useRoute(); const router = useRouter(); const pub = ref(null); const hasAccess = ref(false); const access = ref(null); const paymentOpen = ref(false); const selectedPackage = ref(null); const paymentLoading = ref(false); const paymentError = ref(''); const merchantCode = ref('99485612'); const payment = ref({ method: 'momo_manual', last5_reference: '' }); const isReaderSignedIn = ref(!!localStorage.getItem('public_token'))
async function load () { const { data } = await publicApi.get('/public/publications/' + route.params.slug); pub.value = data; const token = localStorage.getItem('public_token'); if (token) { try { const response = await publicApi.get('/public/publications/' + route.params.slug + '/access'); hasAccess.value = response.data.has_access; access.value = response.data.access; if (response.data.publication) pub.value = { ...pub.value, ...response.data.publication } } catch (error) {} } }
function openPayment (pkg) { selectedPackage.value = pkg; paymentError.value = ''; payment.value = { method: 'momo_manual', last5_reference: '' }; merchantCode.value = '99485612'; paymentOpen.value = true; if (isReaderSignedIn.value) loadMerchantCode() }
function goToReaderAuth () { router.push({ name: 'reader-register', query: { redirect: route.fullPath, package: selectedPackage.value?.id } }) }
async function loadMerchantCode () { try { const { data } = await publicApi.get('/payments/merchant-details'); merchantCode.value = data.merchant_code || '99485612'; if (!data.configured) paymentError.value = 'Merchant payment is not configured yet. Please use PesaPal or contact support.' } catch (error) { merchantCode.value = '99485612' } }
async function submitPayment () { paymentLoading.value = true; paymentError.value = ''; try { if (!isReaderSignedIn.value) { goToReaderAuth(); return } const payload = { method: payment.value.method }; if (payment.value.method === 'momo_manual') payload.last5_reference = payment.value.last5_reference; const { data } = await publicApi.post('/payments/packages/' + selectedPackage.value.id + '/initiate', payload); if (payment.value.method === 'momo_manual') { await publicApi.post('/payments/' + data.payment.id + '/reference', { last5_reference: payment.value.last5_reference }); window.alert('Payment submitted. Admin verification will activate your access.') } else if (data.checkout_url) { window.location.href = data.checkout_url; return } paymentOpen.value = false } catch (error) { const errors = error.response?.data?.errors; paymentError.value = errors ? Object.values(errors).flat().join(' ') : error.response?.data?.message || 'Payment could not be started. Please try again.' } finally { paymentLoading.value = false } }
async function download () { const response = await publicApi.get('/public/publications/' + route.params.slug + '/download', { responseType: 'blob' }); const url = URL.createObjectURL(response.data); const link = document.createElement('a'); link.href = url; link.download = (pub.value.title || 'report') + '.txt'; link.click(); URL.revokeObjectURL(url) }
onMounted(async () => {
  await load()
  const packageId = Number(route.query.package)
  if (packageId && localStorage.getItem('public_token')) {
    const packageToOpen = pub.value?.packages?.find((item) => item.id === packageId)
    if (packageToOpen) openPayment(packageToOpen)
  }
})
</script>
