<template>
  <div class="min-h-screen bg-slate-50">
    <header class="bg-[#0d1d2d] p-5 text-white"><div class="mx-auto max-w-4xl"><RouterLink to="/" class="font-semibold">← Data Bank</RouterLink></div></header>
    <main class="mx-auto max-w-4xl px-4 py-8 sm:px-5">
      <div v-if="pub">
        <div class="text-xs font-semibold uppercase tracking-[0.16em] text-teal-700">{{ pub.category || 'Research' }}</div>
        <h1 class="mt-2 text-3xl font-bold tracking-tight text-slate-900 sm:text-4xl">{{ pub.title }}</h1>
        <p class="mt-4 text-lg leading-8 text-slate-600">{{ pub.summary }}</p>
        <a v-if="pub.youtube_url" :href="pub.youtube_url" target="_blank" rel="noopener noreferrer" class="mt-5 inline-flex items-center gap-2 rounded-xl bg-red-600 px-4 py-3 text-sm font-semibold text-white shadow-sm hover:bg-red-700">Watch related video on YouTube ↗</a>
        <div class="mt-8 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7">
          <div v-if="hasAccess"><div class="mb-4 flex flex-wrap items-center justify-between gap-3 text-xs font-semibold text-emerald-700"><span>ACCESS ACTIVE · EXPIRES {{ access.expires_at ? new Date(access.expires_at).toLocaleString() : 'NEVER' }}</span><button v-if="access.can_download" @click="download" class="rounded-lg bg-[#0d1d2d] px-3 py-2 text-white">Download report</button></div><div class="prose max-w-none whitespace-pre-wrap">{{ pub.content }}</div></div>
          <div v-else><h2 class="text-xl font-semibold text-slate-900">Unlock the full report</h2><p class="mt-2 text-slate-600">Choose a package and payment method. Public summaries and YouTube videos remain free.</p><div class="mt-5 grid gap-3 md:grid-cols-2"><div v-for="pkg in pub.packages" :key="pkg.id" class="rounded-xl border border-slate-200 p-4"><div class="font-semibold">{{ pkg.name }}</div><div class="mt-1 text-lg">UGX {{ Number(pkg.amount_ugx).toLocaleString() }}</div><div class="text-xs text-slate-500">{{ pkg.type === 'reading' ? `${pkg.duration_minutes} minutes` : 'Download licence' }}</div><button @click="openPayment(pkg)" class="mt-3 w-full rounded-lg bg-[#0d1d2d] p-3 font-semibold text-white">Choose payment</button></div></div></div>
        </div>
      </div>
    </main>
    <div v-if="paymentOpen" class="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4" @click.self="paymentOpen = false">
      <section class="w-full max-w-md rounded-3xl bg-white p-6 shadow-2xl sm:p-8"><div class="flex items-start justify-between gap-4"><div><p class="text-xs font-semibold uppercase tracking-[0.16em] text-teal-700">Secure checkout</p><h2 class="mt-1 text-2xl font-semibold text-slate-900">Pay for access</h2></div><button @click="paymentOpen = false" class="rounded-lg border px-3 py-1 text-sm">Close</button></div><div class="mt-5 rounded-2xl bg-slate-50 p-4"><div class="text-sm text-slate-500">{{ selectedPackage?.name }}</div><div class="mt-1 text-2xl font-bold text-slate-900">UGX {{ Number(selectedPackage?.amount_ugx || 0).toLocaleString() }}</div></div><label class="mt-5 block text-sm font-semibold text-slate-700">Payment method<select v-model="payment.method" class="mt-2 w-full"><option value="momo_manual">Mobile Money · merchant code</option><option value="gateway">Card or Mobile Money · payment gateway</option></select></label><p class="mt-2 text-xs leading-5 text-slate-500">{{ payment.method === 'momo_manual' ? 'Pay using the merchant code shown after continuing. Then enter the last five characters of your transaction reference for admin confirmation.' : 'You will enter your number in the payment gateway. The provider will charge the selected amount directly.' }}</p><label class="mt-4 block text-sm font-semibold text-slate-700">{{ payment.method === 'gateway' ? 'Phone or card contact number' : 'Mobile money number' }}<input v-model="payment.phone" required type="tel" placeholder="e.g. 0772 000 000" class="mt-2 w-full" /></label><p v-if="paymentError" class="mt-4 rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{{ paymentError }}</p><button @click="submitPayment" :disabled="paymentLoading || !payment.phone" class="mt-5 w-full rounded-xl bg-teal-700 px-4 py-3.5 font-semibold text-white disabled:opacity-50">{{ paymentLoading ? 'Starting payment...' : payment.method === 'momo_manual' ? 'Continue to merchant payment' : 'Continue to payment gateway' }}</button></section>
    </div>
  </div>
</template>
<script setup>
import { onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import api from '../api/client'
const route = useRoute(); const router = useRouter(); const pub = ref(null); const hasAccess = ref(false); const access = ref(null); const paymentOpen = ref(false); const selectedPackage = ref(null); const paymentLoading = ref(false); const paymentError = ref(''); const payment = ref({ method: 'momo_manual', phone: '' })
async function load () { const { data } = await api.get('/public/publications/' + route.params.slug); pub.value = data; const token = localStorage.getItem('public_token'); if (token) { api.defaults.headers.common.Authorization = 'Bearer ' + token; try { const response = await api.get('/public/publications/' + route.params.slug + '/access'); hasAccess.value = response.data.has_access; access.value = response.data.access; if (response.data.publication) pub.value = { ...pub.value, ...response.data.publication } } catch (error) {} } }
function openPayment (pkg) { if (!localStorage.getItem('public_token')) { router.push({ name: 'reader-register', query: { redirect: route.fullPath, package: pkg.id } }); return } selectedPackage.value = pkg; paymentError.value = ''; paymentOpen.value = true }
async function submitPayment () { paymentLoading.value = true; paymentError.value = ''; try { const { data } = await api.post('/payments/packages/' + selectedPackage.value.id + '/initiate', { phone: payment.value.phone, method: payment.value.method }); if (payment.value.method === 'momo_manual') { const merchant = data.merchant_code || 'the configured merchant code'; const procedure = data.ussd_code || 'the configured USSD procedure'; const reference = window.prompt(`Dial ${procedure}, choose payment, and pay UGX ${Number(selectedPackage.value.amount_ugx).toLocaleString()} to merchant code ${merchant}. Then enter the last 5 characters of your transaction reference:`); if (reference) { await api.post('/payments/' + data.payment.id + '/reference', { last5_reference: reference }); window.alert('Payment submitted. Admin verification will activate your access.') } } else { window.alert(data.message || 'Your payment gateway request has been created.') } paymentOpen.value = false } catch (error) { const errors = error.response?.data?.errors; paymentError.value = errors ? Object.values(errors).flat().join(' ') : error.response?.data?.message || 'Payment could not be started. Please check the number and try again.' } finally { paymentLoading.value = false } }
async function download () { const response = await api.get('/public/publications/' + route.params.slug + '/download', { responseType: 'blob' }); const url = URL.createObjectURL(response.data); const link = document.createElement('a'); link.href = url; link.download = (pub.value.title || 'report') + '.txt'; link.click(); URL.revokeObjectURL(url) }
onMounted(load)
</script>
