<template>
	<div class="space-y-6">
		<div class="flex flex-wrap items-end justify-between gap-4">
			<div><p class="text-xs font-semibold uppercase tracking-[0.16em] text-emerald-700">Knowledge bank</p><h1 class="mt-1 text-2xl font-semibold">Publications</h1><p class="mt-1 text-sm text-slate-500">Manage articles, cover photos, access packages and publishing.</p></div>
			<button @click="openCreate" class="rounded-lg bg-[#0d1d2d] px-4 py-2.5 text-sm font-semibold text-white">+ New publication</button>
		</div>

		<div class="flex flex-wrap items-center gap-3 rounded-xl border bg-white p-4 shadow-sm">
			<input v-model="search" placeholder="Search publications..." class="min-w-[240px] flex-1 rounded-lg border-slate-300" />
			<select v-model="statusFilter" class="rounded-lg border-slate-300"><option value="">All statuses</option><option value="draft">Draft</option><option value="review">Review</option><option value="published">Published</option></select>
			<span class="text-sm text-slate-500">{{ filteredItems.length }} publication{{ filteredItems.length === 1 ? '' : 's' }}</span>
		</div>

		<div v-if="!filteredItems.length" class="rounded-xl border border-dashed bg-white p-10 text-center text-sm text-slate-500">No publications match this search.</div>
		<div v-for="p in filteredItems" :key="p.id" class="overflow-hidden rounded-xl border bg-white shadow-sm">
			<div class="flex flex-col gap-5 p-5 lg:flex-row">
				<img v-if="p.cover_image" :src="p.cover_image" :alt="`${p.title} cover`" class="h-44 w-full rounded-lg object-cover lg:h-32 lg:w-48" />
				<div class="min-w-0 flex-1"><div class="flex flex-wrap items-center gap-2"><span class="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold uppercase text-slate-600">{{ p.status }}</span><span v-if="p.youtube_url" class="rounded-full bg-red-50 px-2.5 py-1 text-xs font-medium text-red-700">YouTube linked</span></div><h2 class="mt-2 text-lg font-semibold text-slate-900">{{ p.title }}</h2><p class="mt-1 line-clamp-2 text-sm text-slate-600">{{ p.summary }}</p><div class="mt-4 flex flex-wrap gap-2"><span v-for="pkg in p.packages" :key="pkg.id" class="rounded-lg border bg-slate-50 px-3 py-2 text-xs text-slate-700">{{ pkg.name }} · UGX {{ Number(pkg.amount_ugx).toLocaleString() }}</span><span v-if="!p.packages?.length" class="rounded-lg border border-dashed px-3 py-2 text-xs text-slate-500">No access packages</span></div></div>
				<div class="flex flex-wrap items-start gap-2 lg:w-56 lg:justify-end"><button v-if="auth.isSuperAdmin && p.status !== 'published'" @click="publish(p)" class="rounded-lg bg-emerald-700 px-3 py-2 text-xs font-semibold text-white">Publish</button><button @click="editPhoto(p)" class="rounded-lg border px-3 py-2 text-xs">Photo</button><button @click="setYoutube(p)" class="rounded-lg border border-red-200 px-3 py-2 text-xs text-red-700">{{ p.youtube_url ? 'Edit YouTube link' : '+ YouTube link' }}</button><button v-if="auth.isSuperAdmin" @click="addPackage(p)" class="rounded-lg border px-3 py-2 text-xs">+ Price package</button></div>
			</div>
		</div>

		<div v-if="showForm" class="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4" @click.self="showForm = false"><form class="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl" @submit.prevent="createPublication"><div class="flex items-start justify-between gap-4"><div><h2 class="text-xl font-semibold">New publication</h2><p class="mt-1 text-sm text-slate-500">Add a clear cover photo from your computer before saving.</p></div><button type="button" @click="showForm = false" class="text-2xl text-slate-400">×</button></div><div class="mt-6 grid gap-4 md:grid-cols-2"><label class="md:col-span-2"><span class="label">Title</span><input v-model="form.title" required class="mt-1 w-full" /></label><label class="md:col-span-2"><span class="label">Public summary</span><textarea v-model="form.summary" required rows="3" class="mt-1 w-full"></textarea></label><label><span class="label">Category</span><input v-model="form.category" placeholder="Research, report, brief..." class="mt-1 w-full" /></label><label><span class="label">YouTube URL</span><input v-model="form.youtube_url" type="url" placeholder="https://youtube.com/..." class="mt-1 w-full" /></label><label class="md:col-span-2"><span class="label">Cover photo</span><input required type="file" accept="image/*" @change="selectPhoto" class="mt-1 block w-full rounded-lg border p-2 text-sm" /><img v-if="photoPreview" :src="photoPreview" alt="Cover preview" class="mt-3 h-40 w-full rounded-lg object-cover" /></label></div><p v-if="formError" class="mt-4 text-sm text-red-600">{{ formError }}</p><div class="mt-6 flex justify-end gap-2"><button type="button" @click="showForm = false" class="rounded-lg border px-4 py-2">Cancel</button><button :disabled="saving" class="rounded-lg bg-[#0d1d2d] px-4 py-2 font-semibold text-white disabled:opacity-50">{{ saving ? 'Saving...' : 'Save draft' }}</button></div></form></div>
	</div>
</template>
<script setup>
import { computed, onMounted, ref } from 'vue'
import api from '../api/client'
import { useAuthStore } from '../store/auth'
const auth = useAuthStore(), items = ref([]), search = ref(''), statusFilter = ref(''), showForm = ref(false), saving = ref(false), formError = ref(''), photo = ref(null), photoPreview = ref('')
const form = ref({ title: '', summary: '', category: '', youtube_url: '' })
const filteredItems = computed(() => items.value.filter((item) => (!statusFilter.value || item.status === statusFilter.value) && (!search.value || `${item.title} ${item.summary}`.toLowerCase().includes(search.value.toLowerCase()))))
async function load() { const { data } = await api.get('/admin/publications'); items.value = data.data || data }
function openCreate() { form.value = { title: '', summary: '', category: '', youtube_url: '' }; photo.value = null; photoPreview.value = ''; formError.value = ''; showForm.value = true }
function selectPhoto(event) { photo.value = event.target.files[0] || null; photoPreview.value = photo.value ? URL.createObjectURL(photo.value) : '' }
async function createPublication() { if (!photo.value) { formError.value = 'A cover photo is required.'; return }; saving.value = true; formError.value = ''; try { const upload = new FormData(); upload.append('photo', photo.value); const uploaded = await api.post('/admin/publications/cover', upload, { headers: { 'Content-Type': 'multipart/form-data' } }); await api.post('/admin/publications', { ...form.value, cover_image: uploaded.data.url, content: '', status: 'draft' }); showForm.value = false; await load() } catch (error) { formError.value = error.response?.data?.message || 'Could not save publication.' } finally { saving.value = false } }
async function addPackage(publication) { const name = window.prompt('Package name (e.g. Read for 2 hours)'); if (!name) return; const amount = Number(window.prompt('Amount in UGX')); if (!amount) return; const mins = Number(window.prompt('Reading duration in minutes (0 for download)') || 0); await api.post(`/admin/publications/${publication.id}/packages`, { name, type: mins ? 'reading' : 'download', duration_minutes: mins || null, amount_ugx: amount, momo_amount_ugx: amount, allows_download: !mins, is_active: true }); load() }
async function setYoutube(publication) { const youtube_url = window.prompt('Paste the public YouTube video or channel URL', publication.youtube_url || ''); if (youtube_url === null) return; await api.put(`/admin/publications/${publication.id}`, { youtube_url: youtube_url || null }); load() }
async function editPhoto(publication) { const input = document.createElement('input'); input.type = 'file'; input.accept = 'image/*'; input.onchange = async () => { const upload = new FormData(); upload.append('photo', input.files[0]); const uploaded = await api.post('/admin/publications/cover', upload, { headers: { 'Content-Type': 'multipart/form-data' } }); await api.put(`/admin/publications/${publication.id}`, { cover_image: uploaded.data.url }); load() }; input.click() }
async function publish(publication) { if (window.confirm('Publish this publication?')) { await api.post(`/admin/publications/${publication.id}/publish`); load() } }
onMounted(load)
</script>